# alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="vim ~/.oh-my-zsh"
alias quit="exit"
alias ls="ls -a"
alias c="clear"
alias refish=". $XDG_CONFIG_HOME/fish/config.fish"
alias mux="tmuxinator"
alias solang="solang-linux-x86-64"
alias drepos="cd /mnt/d/Repos"
alias docker="sudo docker"
alias sol="solana"
alias spl="spl-token"
alias vim="vim -N -u $XDG_CONFIG_HOME/vim/vimrc"
alias nvim="nvim -N -u $XDG_CONFIG_HOME/nvim/init.lua"

